sudo: required
dist: trusty
language: ruby
rvm:
  - ruby-1.9.2-p330
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
before_install:
  - wget https://dl.dropbox.com/u/2175127/libre2-dev_20130802_amd64.deb
  - sudo dpkg -i libre2-dev_20130802_amd64.deb
  - gem install bundler -v '~> 1.11'
