#! /usr/bin/env bash
#
#  script to build gems for all relevant platforms
#
set -o errexit
set -o nounset
set -x

rm -rf tmp pkg gems
mkdir -p gems

# prelude: let's check that things work
bundle update

bundle exec rake clean clobber
bundle exec rake compile
bundle exec rake spec

# MRI et al (standard gem)
bundle exec rake clean clobber
bundle exec rake gem
cp -v pkg/re2*.gem gems

# precompiled native gems ("fat binary")
bundle exec rake gem:native
cp -v pkg/re2*.gem gems

pushd gems
  ls *.gem | sort | xargs sha256sum
popd
