#! /usr/bin/env bash
#
#  run as part of CI
#
if [[ $# -lt 2 ]] ; then
  echo "usage: $(basename $0) <output_dir> <platform>"
  exit 1
fi

set -e -u

OUTPUT_DIR=$1
BUILD_NATIVE_GEM=$2
REF_TYPE=$3

test -e /etc/os-release && cat /etc/os-release

set -x

bundle install --local || bundle install

if [[ "${BUILD_NATIVE_GEM}" == "ruby" ]] ; then
  bundle exec rake clean
  bundle exec rake gem
else
  export MACOSX_DEPLOYMENT_TARGET=10.14
  bundle exec rake gem:${BUILD_NATIVE_GEM}:builder
fi

mkdir -p ${OUTPUT_DIR}
cp -v pkg/*.gem ${OUTPUT_DIR}
ls -l ${OUTPUT_DIR}/*
