#!/usr/bin/env ruby
# frozen_string_literal: true

require "net/http"
require "digest/sha2"
require "yaml"

re2_response = Net::HTTP.get_response(URI("https://github.com/google/re2/releases/latest"))
exit 1 unless re2_response.is_a?(Net::HTTPRedirection)

re2_release = File.basename(URI(re2_response["Location"]).path)
re2_redirect = Net::HTTP.get_response(URI("https://github.com/google/re2/releases/download/#{re2_release}/re2-#{re2_release}.tar.gz"))
exit 1 unless re2_redirect.is_a?(Net::HTTPRedirection)

re2_archive = Net::HTTP.get_response(URI(re2_redirect["Location"]))
exit 1 unless re2_archive.is_a?(Net::HTTPSuccess)
re2_sha256sum = Digest::SHA2.hexdigest(re2_archive.body)

File.write(
  File.expand_path("../dependencies.yml", __dir__),
  {
    "libre2" => { "version" => re2_release, "sha256" => re2_sha256sum },
    "abseil" => { "version" => "20250127.1", "sha256" => "b396401fd29e2e679cace77867481d388c807671dc2acc602a0259eeb79b7811" }
  }.to_yaml
)
