name: Upgrade vendored dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 1 * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
      - name: Upgrade all vendored dependencies to their latest versions
        run: ./scripts/update-dependencies
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: 'upgrade-vendored-dependencies'
          title: 'Upgrade vendored dependencies'
          commit-message: 'Upgrade vendored dependencies to latest versions'
          labels: dependencies
          body: |
            - Upgrade RE2
            - Upgrade Abseil
