name: Precompile native gem

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

permissions:
  contents: read

jobs:
  precompile-gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ports/archives
          key: archives-ubuntu-${{ hashFiles('dependencies.yml') }}
      - run: bundle exec rake "gem:${PLATFORM}"
        env:
          PLATFORM: ${{ inputs.platform }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "cruby-${{ inputs.platform }}-gem"
          path: pkg/*.gem
